server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: scm-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10 #discovery한테 (default:30) 10초마다 하트비트 전송
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    shutdown:
      enabled: true
    web:
      exposure:
        include: "actuator"
